# Generated by Django 4.1.3 on 2023-02-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kissan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('V', 'Vegitable'), ('F', 'Fruits'), ('M', 'Milk'), ('Fi', 'Fish')], max_length=2),
        ),
    ]
