# Generated by Django 4.1.3 on 2023-02-15 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("kissan", "0003_product_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="Product_Added_date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="quantity",
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
