# Generated by Django 4.1.3 on 2023-02-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kissan", "0004_product_product_added_date_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Product_Added_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
